In [1]:
import pandas as pd

In [2]:
aprt_2019=pd.read_csv('./apart/aprt_2018.csv', encoding='euc-kr')
aprt_2019=pd.read_csv('./apart/aprt_2019.csv', encoding='euc-kr')
aprt_2020=pd.read_csv('./apart/aprt_2020.csv', encoding='euc-kr')

In [3]:
aprt_2019.columns

Index(['구', '전용면적', '년', '월', '거래금액', '면적금액', '층', '건축년도', '도로명'], dtype='object')

In [4]:
aprt_2019_median=aprt_2019.groupby([u'구'],as_index=False)[u'전용면적'].median()
aprt_2019_median.rename(columns={u'전용면적':u'전용면적_median'},inplace=True)

In [5]:
aprt_2019_max=aprt_2019.groupby([u'구'],as_index=False)[u'전용면적'].max()
aprt_2019_max.rename(columns={u'전용면적':u'전용면적_max'},inplace=True)

In [6]:
aprt_2019_min=aprt_2019.groupby([u'구'],as_index=False)[u'전용면적'].min()
aprt_2019_min.rename(columns={u'전용면적':u'전용면적_min'},inplace=True)

In [7]:
aprt_2019_mean=aprt_2019.groupby([u'구'],as_index=False)[u'전용면적'].mean()
aprt_2019_mean.rename(columns={u'전용면적':u'전용면적_mean'},inplace=True)

In [8]:
aprt_2019_1=pd.merge(aprt_2019_median,aprt_2019_max, on=None)

In [9]:
aprt_2019_1=pd.merge(aprt_2019_1,aprt_2019_min, on=None)

In [10]:
aprt_2019_1=pd.merge(aprt_2019_1,aprt_2019_mean, on=None)

In [11]:
aprt_2019_1

       구  전용면적_median  전용면적_max  전용면적_min   전용면적_mean
0    강남구     84.85000   272.380   12.9400   92.089181
1    강동구     83.52000   226.940   12.4900   75.007533
2    강북구     79.07000   159.280   12.9900   73.627570
3    강서구     76.11500   192.220   12.2200   72.590566
4    관악구     70.97015   183.400   12.2100   73.109880
5    광진구     84.72000   226.750   13.8300   85.305148
6    구로구     71.49000   199.790   13.2300   72.511262
7    금천구     73.63000   158.200   12.1000   72.722599
8    노원구     59.39000   178.330   12.0600   64.604042
9    도봉구     68.86000   244.790   13.0900   69.810644
10  동대문구     80.53000   170.380   11.9559   71.702185
11   동작구     84.79000   219.510   12.6000   82.609341
12   마포구     84.38840   232.360   12.8500   77.150426
13  서대문구     84.45000   244.610   12.0800   75.772882
14   서초구     84.94300   272.740   18.5300   98.545308
15   성동구     84.41700   241.930   12.8400   79.029901
16   성북구     84.44000   200.530   13.5700   78.103264
17   송파구     84.80000   253.590   15.6400   85.977930
18   양천구     84.23500   238.310   14.0200   82.204079
19  영등포구     79.43000   234.020   10.7800   73.996054
20   용산구     84.96000   253.240   10.0200  102.242087
21   은평구     80.30000   170.100   12.0700   74.710711
22   종로구     84.61400   244.937   12.0100   78.711940
23    중구     84.88000   273.820   14.0800   80.889394
24   중랑구     69.74230   203.770   12.0156   69.853776

In [12]:
aprt_2019_median2=aprt_2019.groupby([u'구'],as_index=False)[u'거래금액'].median()
aprt_2019_median2.rename(columns={u'거래금액':u'거래금액_median'},inplace=True)

In [13]:
aprt_2019_max2=aprt_2019.groupby([u'구'],as_index=False)[u'거래금액'].max()
aprt_2019_max2.rename(columns={u'거래금액':u'거래금액_max'},inplace=True)

In [14]:
aprt_2019_min2=aprt_2019.groupby([u'구'],as_index=False)[u'거래금액'].min()
aprt_2019_min2.rename(columns={u'거래금액':u'거래금액_min'},inplace=True)

In [15]:
aprt_2019_mean2=aprt_2019.groupby([u'구'],as_index=False)[u'거래금액'].mean()
aprt_2019_mean2.rename(columns={u'거래금액':u'거래금액_mean'},inplace=True)

In [16]:
aprt_2019_2=pd.merge(aprt_2019_median2,aprt_2019_max2, on=None)

In [17]:
aprt_2019_2=pd.merge(aprt_2019_2,aprt_2019_min2, on=None)

In [18]:
aprt_2019_2=pd.merge(aprt_2019_2,aprt_2019_mean2, on=None)

In [19]:
aprt_2019_2

       구  거래금액_median  거래금액_max  거래금액_min      거래금액_mean
0    강남구       172000    700000     18000  179967.823834
1    강동구        70000    187000      8900   73737.809095
2    강북구        46000    105000     12400   46805.089734
3    강서구        58450    152000      8000   60390.313736
4    관악구        55400     91000     10500   53545.407118
5    광진구        89000    260000      6900   92629.051146
6    구로구        48500    265000      5400   51020.833900
7    금천구        40500    110000      6500   43298.342667
8    노원구        41500    119000      8500   44402.093960
9    도봉구        37000     95000      9000   40614.378397
10  동대문구        58000    149000      9750   58425.767695
11   동작구        83500    175000     11900   85305.763028
12   마포구        88000    338000     13000   91771.373407
13  서대문구        64000    172000      7000   68038.649791
14   서초구       157000    540000     14000  165307.357835
15   성동구        89700    570000     12000   96499.322709
16   성북구        58000    132000     10500   58499.347073
17   송파구       113000    360000     16000  120140.102817
18   양천구        79000    272000     13500   84712.292872
19  영등포구        69500    366000      9500   76732.695022
20   용산구       124500    840000     16500  151887.365142
21   은평구        51000    127000     10000   52340.261694
22   종로구        79000    242000      7500   79611.942215
23    중구        80000    325000      8500   80259.519763
24   중랑구        44000    122500      8000   44479.230442

In [20]:
aprt_2019_median3=aprt_2019.groupby([u'구'],as_index=False)[u'면적금액'].median()
aprt_2019_median3.rename(columns={u'면적금액':u'면적금액_median'},inplace=True)

In [21]:
aprt_2019_max3=aprt_2019.groupby([u'구'],as_index=False)[u'면적금액'].max()
aprt_2019_max3.rename(columns={u'면적금액':u'면적금액_max'},inplace=True)

In [22]:
aprt_2019_min3=aprt_2019.groupby([u'구'],as_index=False)[u'면적금액'].min()
aprt_2019_min3.rename(columns={u'면적금액':u'면적금액_min'},inplace=True)

In [23]:
aprt_2019_mean3=aprt_2019.groupby([u'구'],as_index=False)[u'면적금액'].mean()
aprt_2019_mean3.rename(columns={u'면적금액':u'면적금액_mean'},inplace=True)

In [24]:
aprt_2019_3=pd.merge(aprt_2019_median3,aprt_2019_max3, on=None)

In [25]:
aprt_2019_3=pd.merge(aprt_2019_3,aprt_2019_min3, on=None)

In [26]:
aprt_2019_3=pd.merge(aprt_2019_3,aprt_2019_mean3, on=None)

In [27]:
aprt_2019_3

       구  면적금액_median  면적금액_max  면적금액_min    면적금액_mean
0    강남구       2008.0      6970       397  2052.030656
1    강동구        963.0      4114       300  1007.349708
2    강북구        634.0      1397       212   665.256999
3    강서구        850.0      1605       213   852.652325
4    관악구        760.0      1347       250   757.858941
5    광진구       1123.0      2225       322  1105.822457
6    구로구        688.0      1557       169   707.516723
7    금천구        565.0      1385       163   619.210000
8    노원구        685.0      1595       261   703.660047
9    도봉구        545.0      1008       245   594.076484
10  동대문구        801.0      1906       295   841.107078
11   동작구       1053.0      2005       284  1066.522632
12   마포구       1185.0      2252       285  1222.077850
13  서대문구        890.0      2285       189   922.637609
14   서초구       1616.0      4337       354  1755.421020
15   성동구       1208.0      4006       402  1245.326693
16   성북구        743.0      1834       222   771.366500
17   송파구       1335.0      3685       394  1440.659927
18   양천구        921.0      2357       232  1038.170455
19  영등포구       1001.0      2317       393  1039.333963
20   용산구       1444.0      3432       367  1463.552021
21   은평구        722.0      1477       220   729.635483
22   종로구        957.0      2339       248  1015.974318
23    중구       1023.5      2001       274  1024.523715
24   중랑구        652.0      1237       263   660.860544

In [28]:
aprt_2019_fin=pd.merge(aprt_2019_1,aprt_2019_2, on=None)

In [29]:
aprt_2019_fin=pd.merge(aprt_2019_fin,aprt_2019_3, on=None)

In [30]:
aprt_2019_fin["연도"]=2019

In [31]:
aprt_2019_fin

,구,전용면적_median,전용면적_max,전용면적_min,전용면적_mean,거래금액_median,거래금액_max,거래금액_min,거래금액_mean,면적금액_median,면적금액_max,면적금액_min,면적금액_mean,연도
0,강남구,84.85000,272.380,12.9400,92.089181,172000,700000,18000,179967.823834,2008.0,6970,397,2052.030656,2019
1,강동구,83.52000,226.940,12.4900,75.007533,70000,187000,8900,73737.809095,963.0,4114,300,1007.349708,2019
2,강북구,79.07000,159.280,12.9900,73.627570,46000,105000,12400,46805.089734,634.0,1397,212,665.256999,2019
3,강서구,76.11500,192.220,12.2200,72.590566,58450,152000,8000,60390.313736,850.0,1605,213,852.652325,2019
4,관악구,70.97015,183.400,12.2100,73.109880,55400,91000,10500,53545.407118,760.0,1347,250,757.858941,2019
5,광진구,84.72000,226.750,13.8300,85.305148,89000,260000,6900,92629.051146,1123.0,2225,322,1105.822457,2019
6,구로구,71.49000,199.790,13.2300,72.511262,48500,265000,5400,51020.833900,688.0,1557,169,707.516723,2019
7,금천구,73.63000,158.200,12.1000,72.722599,40500,110000,6500,43298.342667,565.0,1385,163,619.210000,2019
8,노원구,59.39000,178.330,12.0600,64.604042,41500,119000,8500,44402.093960,685.0,1595,261,703.660047,2019
9,도봉구,68.86000,244.790,13.0900,69.810644,37000,95000,9000,40614.378397,545.0,1008,245,594.076484,2019
10,동대문구,80.53000,170.380,11.9559,71.702185,58000,149000,9750,58425.767695,801.0,1906,295,841.107078,2019
11,동작구,84.79000,219.510,12.6000,82.609341,83500,175000,11900,85305.763028,1053.0,2005,284,1066.522632,2019
12,마포구,84.38840,232.360,12.8500,77.150426,88000,338000,13000,91771.373407,1185.0,2252,285,1222.077850,2019
13,서대문구,84.45000,244.610,12.0800,75.772882,64000,172000,7000,68038.649791,890.0,2285,189,922.637609,2019
14,서초구,84.94300,272.740,18.5300,98.545308,157000,540000,14000,165307.357835,1616.0,4337,354,1755.421020,2019
15,성동구,84.41700,241.930,12.8400,79.029901,89700,570000,12000,96499.322709,1208.0,4006,402,1245.326693,2019
16,성북구,84.44000,200.530,13.5700,78.103264,58000,132000,10500,58499.347073,743.0,1834,222,771.366500,2019
17,송파구,84.80000,253.590,15.6400,85.977930,113000,360000,16000,120140.102817,1335.0,3685,394,1440.659927,2019
18,양천구,84.23500,238.310,14.0200,82.204079,79000,272000,13500,84712.292872,921.0,2357,232,1038.170455,2019
19,영등포구,79.43000,234.020,10.7800,73.996054,69500,366000,9500,76732.695022,1001.0,2317,393,1039.333963,2019
20,용산구,84.96000,253.240,10.0200,102.242087,124500,840000,16500,151887.365142,1444.0,3432,367,1463.552021,2019
21,은평구,80.30000,170.100,12.0700,74.710711,51000,127000,10000,52340.261694,722.0,1477,220,729.635483,2019
22,종로구,84.61400,244.937,12.0100,78.711940,79000,242000,7500,79611.942215,957.0,2339,248,1015.974318,2019
23,중구,84.88000,273.820,14.0800,80.889394,80000,325000,8500,80259.519763,1023.5,2001,274,1024.523715,2019
24,중랑구,69.74230,203.770,12.0156,69.853776,44000,122500,8000,44479.230442,652.0,1237,263,660.860544,2019

In [32]:
aprt_2019_fin.to_csv("aprt_2019_fin.csv", encoding='euc-kr')