In [1]:
import pandas as pd

In [2]:
aprt_2018=pd.read_csv('./apart/aprt_2018.csv', encoding='euc-kr')
aprt_2019=pd.read_csv('./apart/aprt_2019.csv', encoding='euc-kr')
aprt_2020=pd.read_csv('./apart/aprt_2020.csv', encoding='euc-kr')

In [3]:
aprt_2020.columns

Index(['구', '전용면적', '년', '월', '거래금액', '면적금액', '층', '건축년도', '도로명'], dtype='object')

In [4]:
aprt_2020_median=aprt_2020.groupby([u'구'],as_index=False)[u'전용면적'].median()
aprt_2020_median.rename(columns={u'전용면적':u'전용면적_median'},inplace=True)

In [5]:
aprt_2020_max=aprt_2020.groupby([u'구'],as_index=False)[u'전용면적'].max()
aprt_2020_max.rename(columns={u'전용면적':u'전용면적_max'},inplace=True)

In [6]:
aprt_2020_min=aprt_2020.groupby([u'구'],as_index=False)[u'전용면적'].min()
aprt_2020_min.rename(columns={u'전용면적':u'전용면적_min'},inplace=True)

In [7]:
aprt_2020_mean=aprt_2020.groupby([u'구'],as_index=False)[u'전용면적'].mean()
aprt_2020_mean.rename(columns={u'전용면적':u'전용면적_mean'},inplace=True)

In [8]:
aprt_2020_1=pd.merge(aprt_2020_median,aprt_2020_max, on=None)

In [9]:
aprt_2020_1=pd.merge(aprt_2020_1,aprt_2020_min, on=None)

In [10]:
aprt_2020_1=pd.merge(aprt_2020_1,aprt_2020_mean, on=None)

In [11]:
aprt_2020_1

       구  전용면적_median  전용면적_max  전용면적_min  전용면적_mean
0    강남구       84.460   273.680   12.1000  88.019462
1    강동구       81.940   256.360   12.1400  73.581162
2    강북구       84.290   199.960   12.0100  74.925338
3    강서구       73.845   181.170   13.7900  72.418981
4    관악구       76.910   183.400   12.2100  73.627287
5    광진구       84.550   226.750   13.2700  84.249486
6    구로구       66.122   171.220   13.2300  70.970935
7    금천구       59.970   150.720   12.0400  66.724390
8    노원구       59.240   161.010   12.1072  63.193554
9    도봉구       68.860   240.970   13.0200  69.413402
10  동대문구       81.050   213.674   11.4800  73.954285
11   동작구       84.780   244.430   12.7071  81.953813
12   마포구       84.420   232.360   12.8500  77.429261
13  서대문구       84.600   242.390   13.0300  77.840117
14   서초구       84.920   273.860   17.3500  95.646995
15   성동구       84.420   271.380   12.8400  79.551156
16   성북구       84.090   200.530   14.0100  77.680224
17   송파구       84.790   254.415   14.0970  84.763925
18   양천구       78.860   241.510   14.0200  78.943453
19  영등포구       80.920   234.020   12.0500  76.194560
20   용산구       84.940   317.360   13.0100  97.605635
21   은평구       84.170   205.960   12.2300  78.118720
22   종로구       80.850   244.937   12.0900  77.463155
23    중구       84.880   244.470   14.0800  83.482381
24   중랑구       66.254   203.770   12.0156  68.791370

In [12]:
aprt_2020_median2=aprt_2020.groupby([u'구'],as_index=False)[u'거래금액'].median()
aprt_2020_median2.rename(columns={u'거래금액':u'거래금액_median'},inplace=True)

In [13]:
aprt_2020_max2=aprt_2020.groupby([u'구'],as_index=False)[u'거래금액'].max()
aprt_2020_max2.rename(columns={u'거래금액':u'거래금액_max'},inplace=True)

In [14]:
aprt_2020_min2=aprt_2020.groupby([u'구'],as_index=False)[u'거래금액'].min()
aprt_2020_min2.rename(columns={u'거래금액':u'거래금액_min'},inplace=True)

In [15]:
aprt_2020_mean2=aprt_2020.groupby([u'구'],as_index=False)[u'거래금액'].mean()
aprt_2020_mean2.rename(columns={u'거래금액':u'거래금액_mean'},inplace=True)

In [16]:
aprt_2020_2=pd.merge(aprt_2020_median2,aprt_2020_max2, on=None)

In [17]:
aprt_2020_2=pd.merge(aprt_2020_2,aprt_2020_min2, on=None)

In [18]:
aprt_2020_2=pd.merge(aprt_2020_2,aprt_2020_mean2, on=None)

In [19]:
aprt_2020_2

       구  거래금액_median  거래금액_max  거래금액_min      거래금액_mean
0    강남구       172500    670000     15000  180834.208094
1    강동구        82500    249000      8000   83827.100946
2    강북구        55900    128000      7500   55941.708774
3    강서구        65000    162000      7700   67703.281659
4    관악구        64400    136000      9000   61837.525712
5    광진구       105000    269500      8500  106733.933282
6    구로구        52800    170000      6000   54444.654649
7    금천구        44900    125000      8000   47037.735571
8    노원구        48500    157000      8000   52191.458517
9    도봉구        42000    140000      6500   45702.546448
10  동대문구        70000    165000      8500   71194.612018
11   동작구        94000    290000     12400   97813.091554
12   마포구        96500    240000     13300  101302.336872
13  서대문구        74100    176000     11000   78526.264770
14   서초구       170000    550000     15000  175013.143072
15   성동구       108000    670000     12050  114341.003946
16   성북구        69000    149000     11500   68710.921312
17   송파구       123000    410000     18000  130310.826453
18   양천구        80000    294500     11450   88982.112704
19  영등포구        83400    324500      9000   89717.097554
20   용산구       136000    775000     15000  152195.579292
21   은평구        63000    153000      8510   62435.462764
22   종로구        74500    321000      8186   80060.838346
23    중구        90750    304000      8300   92267.565854
24   중랑구        50000    160000      8300   50919.486207

In [20]:
aprt_2020_median3=aprt_2020.groupby([u'구'],as_index=False)[u'면적금액'].median()
aprt_2020_median3.rename(columns={u'면적금액':u'면적금액_median'},inplace=True)

In [21]:
aprt_2020_max3=aprt_2020.groupby([u'구'],as_index=False)[u'면적금액'].max()
aprt_2020_max3.rename(columns={u'면적금액':u'면적금액_max'},inplace=True)

In [22]:
aprt_2020_min3=aprt_2020.groupby([u'구'],as_index=False)[u'면적금액'].min()
aprt_2020_min3.rename(columns={u'면적금액':u'면적금액_min'},inplace=True)

In [23]:
aprt_2020_mean3=aprt_2020.groupby([u'구'],as_index=False)[u'면적금액'].mean()
aprt_2020_mean3.rename(columns={u'면적금액':u'면적금액_mean'},inplace=True)

In [24]:
aprt_2020_3=pd.merge(aprt_2020_median3,aprt_2020_max3, on=None)

In [25]:
aprt_2020_3=pd.merge(aprt_2020_3,aprt_2020_min3, on=None)

In [26]:
aprt_2020_3=pd.merge(aprt_2020_3,aprt_2020_mean3, on=None)

In [27]:
aprt_2020_3

       구  면적금액_median  면적금액_max  면적금액_min    면적금액_mean
0    강남구         2146      5471       449  2086.260052
1    강동구         1116      2456       305  1169.894090
2    강북구          744      1538       171   771.142857
3    강서구          944      1884       206   964.672402
4    관악구          859      1653       281   871.094710
5    광진구         1325      2500       342  1291.935609
6    구로구          745      1750       165   769.805556
7    금천구          704      1622       203   739.437574
8    노원구          814      2126       302   843.929612
9    도봉구          632      1356       155   675.147104
10  동대문구          942      2167       352   995.759938
11   동작구         1184      2737       315  1230.789865
12   마포구         1318      2560       428  1344.650389
13  서대문구          997      2337       252  1038.793946
14   서초구         1755      4378       410  1913.573193
15   성동구         1418      3950       316  1471.162447
16   성북구          884      1962       233   914.518238
17   송파구         1523      4155       315  1601.215907
18   양천구         1013      2765       211  1143.351592
19  영등포구         1138      2694       355  1180.126674
20   용산구         1540      3971       331  1594.043906
21   은평구          817      1741       247   827.602434
22   종로구          911      2590       316  1034.716792
23    중구         1110      2079       143  1135.674146
24   중랑구          745      1580       276   759.866207

In [28]:
aprt_2020_fin=pd.merge(aprt_2020_1,aprt_2020_2, on=None)

In [29]:
aprt_2020_fin=pd.merge(aprt_2020_fin,aprt_2020_3, on=None)

In [30]:
aprt_2020_fin["연도"]=2020

In [31]:
aprt_2020_fin

,구,전용면적_median,전용면적_max,전용면적_min,전용면적_mean,거래금액_median,거래금액_max,거래금액_min,거래금액_mean,면적금액_median,면적금액_max,면적금액_min,면적금액_mean,연도
0,강남구,84.460,273.680,12.1000,88.019462,172500,670000,15000,180834.208094,2146,5471,449,2086.260052,2020
1,강동구,81.940,256.360,12.1400,73.581162,82500,249000,8000,83827.100946,1116,2456,305,1169.894090,2020
2,강북구,84.290,199.960,12.0100,74.925338,55900,128000,7500,55941.708774,744,1538,171,771.142857,2020
3,강서구,73.845,181.170,13.7900,72.418981,65000,162000,7700,67703.281659,944,1884,206,964.672402,2020
4,관악구,76.910,183.400,12.2100,73.627287,64400,136000,9000,61837.525712,859,1653,281,871.094710,2020
5,광진구,84.550,226.750,13.2700,84.249486,105000,269500,8500,106733.933282,1325,2500,342,1291.935609,2020
6,구로구,66.122,171.220,13.2300,70.970935,52800,170000,6000,54444.654649,745,1750,165,769.805556,2020
7,금천구,59.970,150.720,12.0400,66.724390,44900,125000,8000,47037.735571,704,1622,203,739.437574,2020
8,노원구,59.240,161.010,12.1072,63.193554,48500,157000,8000,52191.458517,814,2126,302,843.929612,2020
9,도봉구,68.860,240.970,13.0200,69.413402,42000,140000,6500,45702.546448,632,1356,155,675.147104,2020
10,동대문구,81.050,213.674,11.4800,73.954285,70000,165000,8500,71194.612018,942,2167,352,995.759938,2020
11,동작구,84.780,244.430,12.7071,81.953813,94000,290000,12400,97813.091554,1184,2737,315,1230.789865,2020
12,마포구,84.420,232.360,12.8500,77.429261,96500,240000,13300,101302.336872,1318,2560,428,1344.650389,2020
13,서대문구,84.600,242.390,13.0300,77.840117,74100,176000,11000,78526.264770,997,2337,252,1038.793946,2020
14,서초구,84.920,273.860,17.3500,95.646995,170000,550000,15000,175013.143072,1755,4378,410,1913.573193,2020
15,성동구,84.420,271.380,12.8400,79.551156,108000,670000,12050,114341.003946,1418,3950,316,1471.162447,2020
16,성북구,84.090,200.530,14.0100,77.680224,69000,149000,11500,68710.921312,884,1962,233,914.518238,2020
17,송파구,84.790,254.415,14.0970,84.763925,123000,410000,18000,130310.826453,1523,4155,315,1601.215907,2020
18,양천구,78.860,241.510,14.0200,78.943453,80000,294500,11450,88982.112704,1013,2765,211,1143.351592,2020
19,영등포구,80.920,234.020,12.0500,76.194560,83400,324500,9000,89717.097554,1138,2694,355,1180.126674,2020
20,용산구,84.940,317.360,13.0100,97.605635,136000,775000,15000,152195.579292,1540,3971,331,1594.043906,2020
21,은평구,84.170,205.960,12.2300,78.118720,63000,153000,8510,62435.462764,817,1741,247,827.602434,2020
22,종로구,80.850,244.937,12.0900,77.463155,74500,321000,8186,80060.838346,911,2590,316,1034.716792,2020
23,중구,84.880,244.470,14.0800,83.482381,90750,304000,8300,92267.565854,1110,2079,143,1135.674146,2020
24,중랑구,66.254,203.770,12.0156,68.791370,50000,160000,8300,50919.486207,745,1580,276,759.866207,2020

In [32]:
aprt_2020_fin.to_csv("aprt_2020_fin.csv", encoding='euc-kr')